version: '2'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
  connect:
    image: yc-connect
    ports:
     - 8083:8083
    links:
     - sqlserver
    environment:
     - BOOTSTRAP_SERVERS=<my-kafka-cluster-hostname>:<my-kafka-cluster-port>
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=inventory.configs
     - OFFSET_STORAGE_TOPIC=inventory.offsets
     - STATUS_STORAGE_TOPIC=inventory.statuses
